# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/2022fastai',
                'doc_host': 'https://CJP123.github.io',
                'git_url': 'https://github.com/CJP123/2022fastai',
                'lib_path': '2022fastai'},
  'syms': {'2022fastai.core': {'2022fastai.core.foo': ('core.html#foo', '2022fastai/core.py')}}}